Update contributing
margaritahumanitarian/helpafamily pull request #143
Opened 2021-08-29 15:16 UTC by RedFox0x20

Add additional step regarding `eslint` to help guide new contributors on ensuring their changes follow the styling of the project.

2021-08-29 15:45 UTC, audreyfeldroy requested changes
Thanks for thinking to add this @RedFox0x20. It'll save a lot of reviewer time. I added `yarn format` separately, but perhaps we can soon combine those two into the same `yarn format` command.

2021-08-29 15:45 UTC, audreyfeldroy commented on CONTRIBUTING.md
> +4. Run `eslint . --fix` to ensure your code is following our linter rules, you may have to fix some issues manually.
```suggestion
4. Run `eslint . --fix` and `yarn format` to ensure your code is following our linter rules. You may have to fix some issues manually.
```

2021-08-29 15:52 UTC, RedFox0x20 commented
> Thanks for thinking to add this @RedFox0x20. It'll save a lot of reviewer time. I added `yarn format` separately, but perhaps we can soon combine those two into the same `yarn format` command.

Yes, when I saw your changes I thought this too haha. Added your text changes to the commit too.

2021-08-31 11:37 UTC, audreyfeldroy approved these changes
Nice work combining the commands into `yarn format` @RedFox0x20. Merging this, thanks!

2021-08-31 11:37 UTC, merged