Add 404 page
margaritahumanitarian/helpafamily pull request #144
Opened 2021-08-29 16:50 UTC by pydanny

This pull request adds a very simple 404 page.

2021-08-29 17:09 UTC, ozer619 commented
Hi @pydanny thank you so much for your contribution !! The implementation is really a great!! start 

The content looks really great and fonts are perfect too

I noticed that the 404 template appears a bit compressed :
![Screenshot_20210829_222455](https://user-images.githubusercontent.com/51698593/131258658-cae70e7c-eec9-423c-abd3-ae16e1cc637a.png)

Take a look at the code for the thank you page as an example of a page that uses a simpler layout .
Perhaps you can use same layout component . experiment with that and let us know if u need any help updating this PR.
You can find us in the chat https://app.element.io/#/room/#mhf:matrix.org ask us if u need further guidance.

2021-08-29 17:14 UTC, ozer619 requested changes
I have suggested a change to CardParagraph to make the 404 page more descriptive.

2021-08-29 17:14 UTC, ozer619 commented on pages/404.js
> +        <CardParagraph>{'Always act in kindness'}</CardParagraph>
```suggestion
        <CardParagraph>{' The Page you requested was not found.  Always act in kindness by reporting this at https://github.com/margaritahumanitarian/helpafamily/issues/new/choose'}</CardParagraph>
```

2021-08-29 17:26 UTC, audreyfeldroy requested changes
@ozer619 I've left you a practice task to get you familiar with the GitHub PR review tools for suggesting changes.

2021-08-29 17:26 UTC, audreyfeldroy commented on pages/404.js
> +            ' The page you requested was not found. Always act in kindness by reporting errors like this at https://github.com/margaritahumanitarian/helpafamily/issues/new/choose'
```suggestion
            'The page you requested was not found. Always act in kindness by reporting errors like this at https://github.com/margaritahumanitarian/helpafamily/issues/new/choose'
```

2021-08-29 17:26 UTC, audreyfeldroy commented on pages/404.js
> +            ' The page you requested was not found. Always act in kindness by reporting errors like this at https://github.com/margaritahumanitarian/helpafamily/issues/new/choose'
Take a look at https://nextjs.org/docs/api-reference/next/link and see if you can implement a hyperlink using the `Link` component.

@ozer619 would you like to "Insert a suggestion" via the GitHub PR review tool that does this?

2021-09-03 04:59 UTC, ozer619 requested changes

2021-09-03 04:59 UTC, ozer619 commented on pages/404.js
> +            ' The page you requested was not found. Always act in kindness by reporting errors like this at https://github.com/margaritahumanitarian/helpafamily/issues/new/choose'
```suggestion
 'The page you requested was not found. Always act in kindness by reporting errors like this at'}
<Link href="https://github.com/margaritahumanitarian/helpafamily/issues/new/choose"
{"here"}
</Link>           
```

2021-09-10 15:17 UTC, RedFox0x20 commented
Replaced by #183

2021-09-10 15:17 UTC, closed without merging