style improvement
margaritahumanitarian/helpafamily pull request #175
Opened 2021-09-08 10:33 UTC by theflucs

2021-09-08 17:25 UTC, RedFox0x20 requested changes
Great stuff @theflucs !

This is much nicer on the eyes and provides a much more _modern_ design that is less blocky and provides good visual focal points to the user.

2021-09-08 17:25 UTC, RedFox0x20 commented on pages/give-devices.js
> +        <div className="p-12">
Might be worth changing this to `sm:p-12` the reason being that on smaller devices (such as phones) this padding can be quite significant as it squashes the text together. Having no padding on these devices appears to work quite well and makes good use of the extra space given to it.

Noting: The updating of the CSS breakpoints does not appear to work properly on the Vercel host for me currently, however this should provide improved responsiveness.

2021-09-09 08:53 UTC, RedFox0x20 approved these changes
Perfect, scales down to mobile devices better now. Thanks for the contribution!

2021-09-09 11:54 UTC, marekrozmus approved these changes
I love it  :) - I was thinking about some UI improvements while doing #173 but I don't have the skills for that ;) Hopefully there won't be much conflicts when merging both PRs.

2021-09-10 05:13 UTC, audreyfeldroy approved these changes
@theflucs Both the code and the page are beautiful! Nice work and I appreciate your eye for detail here so much.

2021-09-10 05:14 UTC, merged