Fixed lighthouse lhci command not working
margaritahumanitarian/helpafamily pull request #190
Opened 2021-09-15 10:54 UTC by ozer619

The lhci command now works perfectly.

2021-09-15 16:20 UTC, RedFox0x20 requested changes

2021-09-15 16:20 UTC, RedFox0x20 commented on .github/workflows/lighthouse.yml
> +          yarn
Probably a good idea to be specific with this and use `yarn install`

2021-09-16 21:03 UTC, RedFox0x20 approved these changes

2021-09-18 19:22 UTC, audreyfeldroy approved these changes
All looks great @ozer619, thank you!

2021-09-18 19:22 UTC, audreyfeldroy commented on lighthouserc.js
> +      startServerCommand: 'yarn start',
For anyone wondering about this: @ozer619 says `yarn start` starts the server with settings optimized for production.

2021-09-18 19:23 UTC, merged