Add test framework and some tests
margaritahumanitarian/helpafamily pull request #192
Opened 2021-09-16 20:32 UTC by marekrozmus

Closes #2 

Added some config based on docs and added tests for main form.

Needed to change the hook a little to make it more testable ;)

2021-09-17 19:22 UTC, RedFox0x20 requested changes
Changes appear to work as expected and the site continues to work correctly. Unfortunately I cannot provide a very useful review as I am unfamiliar with Jest, however the code for creating tests appears simple to configure and easy to maintain.

2021-09-17 19:22 UTC, RedFox0x20 commented on .gitignore
> +/.vscode/
Please add a newline to the end of the file, this can cause problems on some system configurations and GitHub doesn't seem to be a fan of it either.

2021-09-19 01:19 UTC, LowLifeArcade commented on __tests__/components/MainDonationForm.spec.js
> +
A test comment

2021-09-19 09:56 UTC, RedFox0x20 approved these changes

2021-09-20 01:55 UTC, audreyfeldroy requested changes
This is amazing @marekrozmus, thank you! I made a few little suggestions but it looks solid.

2021-09-20 01:55 UTC, audreyfeldroy commented on __tests__/components/MainDonationForm.spec.js
> +  it('should render switch, select and button', () => {
```suggestion
  it('should render toggle switch, dropdown select combo box, and bottom button', () => {
```

2021-09-20 01:55 UTC, audreyfeldroy commented on __tests__/components/MainDonationForm.spec.js
> +  it('should render switch, select and button', () => {
Looks like this test could use an `expect` to check rendering of the first item (the toggle switch). 🙂

2021-09-20 01:55 UTC, audreyfeldroy commented on __tests__/components/MainDonationForm.spec.js
> +  it('should show error dialog if amount not selected', () => {
```suggestion
  it('should show error dialog if the form is submitted without an amount selected', () => {
```

2021-09-20 01:55 UTC, audreyfeldroy commented on __tests__/components/MainDonationForm.spec.js
> +  it('should not show error when amount selected and submit the form', () => {
```suggestion
  it('should not show an error when the form is submitted with an amount correctly selected', () => {
```

2021-09-20 01:55 UTC, audreyfeldroy commented on __tests__/components/MainDonationForm.spec.js
> +import userEvent from '@testing-library/user-event';
```suggestion
import userEvent from '@testing-library/user-event';
```

2021-09-22 18:07 UTC, LowLifeArcade approved these changes
@audreyfeldroy and I reviewed this together over screen share. All looks great! 🥳

2021-09-22 18:07 UTC, LowLifeArcade commented on components/FallPreventionForEldersCard.js
> +  const handleOnClick = () =>
We studied a bit more closely and understand better now that it has to do with the hooks efficiency. We'd love to hear more about it in chat sometime.

2021-09-22 18:08 UTC, audreyfeldroy approved these changes

2021-09-22 18:20 UTC, merged

2021-09-22 18:20 UTC, audreyfeldroy commented
Merged, thanks again @marekrozmus!

2021-09-23 00:46 UTC, audreyfeldroy commented
Thanks for all your reviewing help @RedFox0x20 @LowLifeArcade @pydanny  🙏