Dependabot updates
margaritahumanitarian/helpafamily pull request #204
Opened 2021-09-28 21:29 UTC by RedFox0x20

The Dependabot system identified the vulnerability [CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw) a ReDoS (Regular Expression Denial of Service) within the ansi-regex package. This has been identified as a moderate severity issue. Here it is a dependency of a package we use however it is still worth updating in recognition of the warning
> ansi-regex is vulnerable to Inefficient Regular Expression Complexity
suggesting that for complex Regular Expressions, the time complexity increases greater than it potentially should have leading to a DOS vulnerability.

2021-09-29 19:59 UTC, marekrozmus requested changes
Could you please check the result of command:

`yarn why ansi-regex`

```
yarn why v1.22.10
[1/4] Why do we have the module "ansi-regex"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ansi-regex@5.0.0"
info Reasons this module exists
   - "@testing-library#dom#pretty-format" depends on it
   - Hoisted from "@testing-library#dom#pretty-format#ansi-regex"
   - Hoisted from "wrap-ansi#strip-ansi#ansi-regex"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "20KB"
info Disk size with transitive dependencies: "20KB"
info Number of shared dependencies: 0
```

Maybe it would be better to update the dependency we are using  and not fixing the dependency of dependency ;)?

Please try update our dependencies and see if problem still exists :)

2021-09-30 16:30 UTC, RedFox0x20 commented
Sorry that's not a part of my concern here, I have created #212 for such a task to be performed under. This PR is simply to fix a potential security and performance issue highlighted and generated by Dependabot.

2021-10-03 01:43 UTC, audreyfeldroy commented
I appreciate you noticing and submitting this fix @RedFox0x20! Looks like we have an upstream dependency fix in #220 now. If that one takes too long to bring in and you want to merge this PR as a temporary intermediate security fix, I'm fine with it.

And thank you @marekrozmus for the suggestion and review, and @RedFox0x20 for filing and assigning that to a new contributor, nice!

2021-10-03 13:04 UTC, marekrozmus approved these changes
LGTM

2021-10-03 15:43 UTC, merged