update tailwind.config for responsivness && add multi column layout w…
margaritahumanitarian/helpafamily pull request #61
Opened 2021-08-18 22:03 UTC by GrungeKarma

…ith mobile responsiveness

standardized the mobile responsiveness in the tailwind.config added responsive div containers that add a multicolumn layout for nonmobile screens and keeps the single on mobile screens.

2021-08-18 22:05 UTC, GrungeKarma commented
Just submitted an updated pull request. Sorry about the confusion.

2021-08-18 23:01 UTC, RedFox0x20 requested changes
Responsive to size changes and looks reasonable.

If implemented it would be a good idea to start looking at #38

There's only the one highlighted issue in `index.js`.
The Donation form also appears slightly squashed.

2021-08-18 23:17 UTC, GrungeKarma commented on pages/index.js
> +    <div className="w-screen">
Removed the extraneous CSS.  I think the donation form size should be addressed with issue #38.

2021-08-18 23:50 UTC, RedFox0x20 commented on pages/index.js
> +    <div className="w-screen">
Yes I think it would suit #38 too as more of a standardisation of panel sizes.

2021-08-18 23:51 UTC, RedFox0x20 approved these changes
All appears okay to me, the issue I previously mentioned is now fixed.

All seems well with reference to the comments above.

2021-08-19 03:51 UTC, audreyfeldroy commented
Fantastic work @GrungeKarma!

I reviewed the diff in detail. It's extremely clean and elegant. The multi-column layout works very nicely, and you've gone above and beyond with implementing responsiveness too. 

Thank you for all your hard work. Your contribution is truly appreciated.

2021-08-19 03:51 UTC, merged