button lift and text shadow
margaritahumanitarian/helpafamily pull request #80
Opened 2021-08-19 19:16 UTC by tof-tof

added button lift on hover
added extra shadow to buttons to help it stand out from the cards
set the tracking on the buttons to be a bit wider as the text as upper case
added background shadow to directionary text

resolve #14

2021-08-19 19:31 UTC, RedFox0x20 commented
Please note the linter issues were previously fixed in a couple commits that your branch is behind on. It's important to pull the latest commits before creating a PR. :)

2021-08-19 19:54 UTC, audreyfeldroy commented
I love what you did here @tof-tof! These sorts of subtle style and UX improvements to delight the visitor are wonderful.

Thank you @RedFox0x20 for providing friendly guidance here. I appreciate you pitching in on the review side so much!

Yep, the best time to pull commits from the `main` branch is before the PR. The next best time is after you submit the PR and realize your branch is behind...nice work pulling and updating your PR, and fixing the lint error 🙂 

I'm in meetings for awhile, but I'll follow up later with a more detailed technical review of your diff.

2021-08-20 01:57 UTC, audreyfeldroy commented on pages/_app.js
> +// import 'tailwindcss/tailwind.css';
```suggestion
```

2021-08-20 02:01 UTC, audreyfeldroy commented
The diff looks good. I'm still getting the hang of Tailwind CSS and am a bit tired, so I'd actually like to revisit the rest of this review tomorrow with fresh eyes.

@marekrozmus if you'd like, you're welcome to review and merge this before I return tomorrow.

2021-08-20 06:05 UTC, marekrozmus requested changes
@audreyfeldroy I'm not huge fan of lifting buttons as we are changing here default behaviour and look and feel of `daisyui` but if you like it then go ahead 🙂

2021-08-20 06:05 UTC, marekrozmus commented on pages/_app.js
> +import '../styles/global.css';
Please group the local imports below the external modules like:
```javascript
import PropTypes from 'prop-types';
import React from 'react';

import '../styles/global.css';
```

2021-08-20 06:05 UTC, marekrozmus commented on styles/global.css
> +
Please remove empty line

2021-08-21 04:11 UTC, audreyfeldroy commented
Thanks for the feedback about changing default daisyUI behavior @marekrozmus. It's a good point. Custom behavior does increase the maintenance effort on our side. I've given it serious consideration. My read of daisyUI is that it's like Bootstrap, where default components are provided but it's common/expected to customize the styles. https://daisyui.com/docs/customize looks like it encourages customization.

Here the lift and shadow behavior adds enough improvement that I'd like to accept this PR. It's also subtle enough that I see it as compatible with #76.

I do think it's the sort of change that could potentially be useful upstream to daisyUI. @tof-tof before I recommend that you submit an upstream PR: 

@saadeghi Hey, would you be interested in a daisyUI PR for the button lift and/or text shadow in this PR? See it in action in the Netlify deploy preview above.

2021-08-21 04:22 UTC, pydanny approved these changes
Looks good to me.

2021-08-21 04:22 UTC, merged

2021-08-21 04:24 UTC, pydanny commented
@tof-tof Awesome PR! 👍🏻

2021-08-21 04:43 UTC, saadeghi commented
@audreyfeldroy I encourage everyone to customize design decisions for their projects. Thanks to Tailwind's utility classes it's easy to customize things.